SET(CMAKE_INCLUDE_PATH ${OE_LIB_DIR}/sdlttf/include)
SET(CMAKE_LIBRARY_PATH ${OE_LIB_DIR}/sdlttf/lib)

INCLUDE(${CMAKE_ROOT}/Modules/FindSDL_ttf.cmake)
INCLUDE(${OE_CURRENT_EXTENSION_DIR}/SetupSDL_ttf.cmake)
